apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
type: Opaque
data:
  mySqlRootPassword: {{ .Values.auth.rootPassword | b64enc }}
  mySqlUser: {{ .Values.auth.user | b64enc }}
  mySqlPassword: {{ .Values.auth.password | b64enc }}
 